version: '3.1'
services: 
    fblocal:
        build: 
            context: .
            dockerfile: docker/Dockerfile
        image: fblocal
        ports: 
            - 9099:9099 # Authentication
        volumes: 
            - .:/work
            - "/var/run/docker.sock:/var/run/docker.sock"

