name: Build docker image

# verify docker build is functional

on:
  push:

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build Docker image
        uses: docker/build-push-action@v6.15.0
        with:
          context: .
          push: false
          file: ./docker/Dockerfile
          platforms: linux/amd64,linux/arm64
