name: No secrets in commits

on:
  push:

jobs:
  check-no-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
      - name: run gitleaks
        run: |
          docker run --rm -v "`pwd`:/path" zricethezav/gitleaks:v8.15.2 detect --source="/path" -v
      - name: Scan using tartufo
        uses: godaddy/tartufo-action@v4.0.1
